"""empty message

Revision ID: f26a8807cf98
Revises: 
Create Date: 2021-10-20 01:58:21.609835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26a8807cf98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runnings',
    sa.Column('id', sa.Integer(), nullable=False, comment='기본키'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 기본키'),
    sa.Column('category', sa.String(length=20), server_default='private', nullable=False, comment='private, open 으로 구분'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='러닝 모드'),
    sa.Column('invite_code', sa.String(length=10), nullable=False, comment='private 일 경우 필요한 코드'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='현재 방의 상태'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성된 시간'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정된 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_running_histories',
    sa.Column('id', sa.Integer(), nullable=False, comment='기본키'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 기본키'),
    sa.Column('running_participant_id', sa.Integer(), nullable=False, comment='달리기 참가자 기본키'),
    sa.Column('distance', sa.SmallInteger(), nullable=False, comment='거리'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성된 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='기본키'),
    sa.Column('nickname', sa.String(length=45), nullable=False, comment='별명'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='탈퇴: out'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성된 시간'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정된 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_running_histories')
    op.drop_table('runnings')
    # ### end Alembic commands ###
